Connect action with component Milestone 3 code review
dipbazz/bookstore-cms pull request #3
Opened 2021-05-15 04:20 UTC by dipbazz

In this pull request, I have connected the redux action `createBook` and removeBook` to add and remove a book from the store.

Changes in the `BooksForm` component
-

- Made it stateful to have its own state with `title` and `category` of a book.
- Add methods 
    - `handleTitleChange` that handles the change in title input and store the value in the local state.
    - `handleCategoryChange` that handles the change in the category and store the value in the local state, and 
    - `handleSubmit` which submits the form and store the local title, and category to the redux store
- Add function `mapDispatchToProps` to map the `createBook` action to props which saves the local state to redux store.

changes in `BookList` and `Book` component
-

- Made `BookList` component to be stateful to take `removeBook` action as props
- Passed `handleRemoveBook` event to `Book` component as props
- `Book` component takes the `handleRemoveBook` function as props and dispatches the `removeBook` action on click event.

Any feedback and suggestions is appreciated.

2021-05-15 06:39 UTC, uche-inyama requested changes
## Changes Required

### Hi dipbazz :wave: 

This milestone is coming along fine. But it would be nice if you refactor the handleChange method. I will leave an inline comment on how to go about it.

#### That's it, refactor those lines of code, then submit another form for a code review.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-05-15 06:39 UTC, uche-inyama commented on src/containers/BooksForm.js
> +
A single method like so, will be fine:

```
handleChange({ target: { name, value } }) {
  this.setState({
    [name]: value,
  })
}


```

You have to add **name attribute** to input and select tags in the form.

2021-05-15 06:39 UTC, uche-inyama commented on src/containers/BooksForm.js
> +              {categories.map((item) => <option key={item} value={item}>{item}</option>)}
Remember to add **name attribute** to input and select tags.

2021-05-15 06:39 UTC, uche-inyama commented on src/containers/BooksForm.js
> +    this.handleCategoryChange = this.handleCategoryChange.bind(this);
Just a single bind would do: 

**``` this.handleChange = this.handleChange.bind(this)```**

2021-05-16 22:15 UTC, Forison approved these changes
## Status::Approved✔️

#### Good job on refactoring the code as requested earlier, the code is much cleaner and more readable. Kindly go ahead and merge the branch and proceed to the next milestone👷.

#### Happy coding👨‍💻

Addo Forison

2021-05-16 22:15 UTC, Forison commented on src/containers/BooksForm.js
> +  handleChange({ target: { name, value } }) {
**[Optional]**
React allows you to skip the binding step in line 14 and 15 if the functions are defined with the arrow function. This way you can have `handleChange=({ target: { name, value } })=>{ ` without binding in constructor.

2021-05-17 08:18 UTC, merged